main = "build"
project = "rana-socketd"

[[vendor]]
name = "tomlplusplus"
url = "https://raw.githubusercontent.com/marzer/tomlplusplus/v3.4.0/toml.hpp"
sha256 = "6b5172ad4dd6519aec67b919181fa7a38a2234131e5b2afa232dfe444819783e"
dest = "root://vendor/"
create_directory = true

[[stages]]
name = "vendor"
type = "vendor"

[[stages]]
name = "build"
type = "premake5"
depends = ["vendor"]
clean = true
outputs = ["root://socket/bin/Release/rana-socketd"]

[[stages]]
name = "clean"
type = "clean"
targets = ["build"]
paths = [
  "root://socket/bin",
  "root://socket/obj",
  "root://serializer/bin",
  "root://serializer/obj",
  "root://serializer/lib",
  "root://client/cpp/bin",
  "root://client/cpp/obj",
]
