# automatically generated by the FlatBuffers compiler, do not modify

# namespace: rana

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class McAction(object):
    Start = 0
    Stop = 1
    Restart = 2


class PowerAction(object):
    Shutdown = 0
    Standby = 1
    Reboot = 2


class MediaAction(object):
    Play = 0
    Pause = 1
    PlayPause = 2
    Stop = 3


class LightAction(object):
    Toggle = 0
    On = 1
    Off = 2


class CommandPayload(object):
    NONE = 0
    McServerCmd = 1
    VolumeCmd = 2
    PowerCmd = 3
    PlayMovieCmd = 4
    LaunchBrowserCmd = 5
    MediaCmd = 6
    LookupMachineCmd = 7
    SpeakCmd = 8
    LightCmd = 9
    TalkCmd = 10


class Status(object):
    OK = 0
    UNKNOWN_COMMAND = 1
    TYPE_MISMATCH = 2
    EXECUTION_FAILED = 3
    INVALID_PAYLOAD = 4
    FORBIDDEN = 5
    SAFETY_GATE_FAILED = 6
    FORWARD_TO_CLIENT = 7


class McServerCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = McServerCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMcServerCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # McServerCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # McServerCmd
    def Action(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # McServerCmd
    def WorldName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def McServerCmdStart(builder):
    builder.StartObject(2)

def McServerCmdAddAction(builder, action):
    builder.PrependInt8Slot(0, action, 0)

def McServerCmdAddWorldName(builder, worldName):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(worldName), 0)

def McServerCmdEnd(builder):
    return builder.EndObject()



class VolumeCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VolumeCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVolumeCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VolumeCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VolumeCmd
    def Level(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # VolumeCmd
    def Mute(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def VolumeCmdStart(builder):
    builder.StartObject(2)

def VolumeCmdAddLevel(builder, level):
    builder.PrependUint8Slot(0, level, 0)

def VolumeCmdAddMute(builder, mute):
    builder.PrependBoolSlot(1, mute, 0)

def VolumeCmdEnd(builder):
    return builder.EndObject()



class PowerCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PowerCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPowerCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PowerCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PowerCmd
    def Action(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # PowerCmd
    def Confirm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def PowerCmdStart(builder):
    builder.StartObject(2)

def PowerCmdAddAction(builder, action):
    builder.PrependInt8Slot(0, action, 0)

def PowerCmdAddConfirm(builder, confirm):
    builder.PrependBoolSlot(1, confirm, 0)

def PowerCmdEnd(builder):
    return builder.EndObject()



class PlayMovieCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlayMovieCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlayMovieCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PlayMovieCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlayMovieCmd
    def Path(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PlayMovieCmd
    def StartSeconds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def PlayMovieCmdStart(builder):
    builder.StartObject(2)

def PlayMovieCmdAddPath(builder, path):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(path), 0)

def PlayMovieCmdAddStartSeconds(builder, startSeconds):
    builder.PrependUint64Slot(1, startSeconds, 0)

def PlayMovieCmdEnd(builder):
    return builder.EndObject()



class LaunchBrowserCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LaunchBrowserCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLaunchBrowserCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LaunchBrowserCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LaunchBrowserCmd
    def Url(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def LaunchBrowserCmdStart(builder):
    builder.StartObject(1)

def LaunchBrowserCmdAddUrl(builder, url):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(url), 0)

def LaunchBrowserCmdEnd(builder):
    return builder.EndObject()



class MediaCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MediaCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMediaCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MediaCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MediaCmd
    def Action(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # MediaCmd
    def Target(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def MediaCmdStart(builder):
    builder.StartObject(2)

def MediaCmdAddAction(builder, action):
    builder.PrependInt8Slot(0, action, 0)

def MediaCmdAddTarget(builder, target):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(target), 0)

def MediaCmdEnd(builder):
    return builder.EndObject()



class LookupMachineCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LookupMachineCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLookupMachineCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LookupMachineCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LookupMachineCmd
    def Subnet(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LookupMachineCmd
    def TimeoutMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def LookupMachineCmdStart(builder):
    builder.StartObject(2)

def LookupMachineCmdAddSubnet(builder, subnet):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(subnet), 0)

def LookupMachineCmdAddTimeoutMs(builder, timeoutMs):
    builder.PrependUint32Slot(1, timeoutMs, 0)

def LookupMachineCmdEnd(builder):
    return builder.EndObject()



class SpeakCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SpeakCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSpeakCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SpeakCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SpeakCmd
    def Text(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SpeakCmdStart(builder):
    builder.StartObject(1)

def SpeakCmdAddText(builder, text):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(text), 0)

def SpeakCmdEnd(builder):
    return builder.EndObject()



class LightCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LightCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLightCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LightCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LightCmd
    def Room(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LightCmd
    def Action(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def LightCmdStart(builder):
    builder.StartObject(2)

def LightCmdAddRoom(builder, room):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(room), 0)

def LightCmdAddAction(builder, action):
    builder.PrependInt8Slot(1, action, 0)

def LightCmdEnd(builder):
    return builder.EndObject()



class TalkCmd(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TalkCmd()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTalkCmd(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TalkCmd
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TalkCmd
    def Audio(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return None

    # TalkCmd
    def Encoding(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TalkCmd
    def SampleRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # TalkCmd
    def Channels(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def TalkCmdStart(builder):
    builder.StartObject(4)

def TalkCmdAddAudio(builder, audio):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(audio), 0)

def TalkCmdAddEncoding(builder, encoding):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(encoding), 0)

def TalkCmdAddSampleRate(builder, sampleRate):
    builder.PrependUint32Slot(2, sampleRate, 0)

def TalkCmdAddChannels(builder, channels):
    builder.PrependUint8Slot(3, channels, 0)

def TalkCmdEnd(builder):
    return builder.EndObject()



class Command(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Command()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Command
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Command
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Command
    def PayloadType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Command
    def Payload(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def CommandStart(builder):
    builder.StartObject(3)

def CommandAddRequestId(builder, requestId):
    builder.PrependUint64Slot(0, requestId, 0)

def CommandAddPayloadType(builder, payloadType):
    builder.PrependUint8Slot(1, payloadType, 0)

def CommandAddPayload(builder, payload):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)

def CommandEnd(builder):
    return builder.EndObject()



class Response(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Response()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Response
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Response
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Response
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Response
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ResponseStart(builder):
    builder.StartObject(3)

def ResponseAddRequestId(builder, requestId):
    builder.PrependUint64Slot(0, requestId, 0)

def ResponseAddStatus(builder, status):
    builder.PrependInt8Slot(1, status, 0)

def ResponseAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def ResponseEnd(builder):
    return builder.EndObject()



